from linkedList import *


lst = LinkedList()
lst.append(1)
lst.append(2)
lst.append(3)
lst.print_list()
lst.insert(0, 0)
lst.print_list()
lst.reverse()
lst.print_list()
lst.sort()
lst.print_list()
lst.remove(2)
lst.print_list()
lst.pop(0)
lst.print_list()
lst.append(5)
lst.append(4)
lst.append(3)
lst.print_list()
print(lst.count(0))

lst2 = LinkedList()
lst2.append(1)
lst2.append(2)
lst2.append(3)
lst2.print_list()
lst.extend(lst2)
lst.print_list()
lst.remove(1)
lst.remove(1)
lst.remove(3)
lst.remove(3)
lst.remove(3)
lst.print_list()
